export min_memory="${MIN_MEMORY}"
export max_memory="${MAX_MEMORY}"
export bucket_namespace="${BUCKET_NAMESPACE}"
export bucket_name="${BUCKET_NAME}"
export minecraft_server_jar_download_url="${SERVER_JAR_DOWNLOAD_URL}"